enum PAGE {
  /** 首页 */
  INDEX = '/pages/index/index',
  /** 档案 */
  ARCHIVES = '/pages/archives/index',
  /** 消息中心 */
  MESSAGE_CENTER = '/pages/message/index',
  /** 我的 */
  ME = '/pages/me/index',
  /** 个人资料 */
  PROFILE = '/pages/settings/profile/index',
  /** 个人资料 */
  CERTIFICATION = '/pages/settings/certification/index',
  /** 授权页面 */
  AUTHORIZE = '/pages/authorize/index',
  /** 支付中心 */
  CASHIER = '/pages/cashier/index',
  /** 支付结果页 */
  CASHIER_RESULT = '/pages/cashier/result/index',
  /** 医生详情 */
  DOCTOR = '/pages/doctor/index',
  /** 我的医生 */
  MY_DOCTOR = '/pages/doctor/my-doctor/index',
  /** 搜索页 */
  DOCTOR_SEARCH = '/pages/doctor/search/index',
  /** 二维码结果页 */
  DOCTOR_SCAN = '/pages/doctor/scan/index',
  /** 医生关注列表 */
  DOCTOR_FOLLOW_LIST = '/pages/doctor/follow/index',
  /** 文章详情 */
  ARTICLE = '/pages/article/index',
  /** 文章列表 */
  ARTICLE_LIST = '/pages/article/list/index',
  /** 文章收藏列表 */
  ARTICLE_BOOKMARK_LIST = '/pages/article/bookmark/index',
  /** 专栏文章列表 */
  ARTICLE_COLUMN__LIST = '/pages/article/column/index',
  /** 帮助中心 */
  HELP_CENTER = '/pages/help/list/index',
  /** 帮助详情 */
  HELP = '/pages/help/index',
  /** 关于我们 */
  ABOUT = '/pages/settings/about/index',
  /** WEBVIEW */
  WEBVIEW = '/pages/webview/index',
  /** 我的处方列表 **/
  PRESCRIBE_LIST = '/pages/prescribe/order/list/index',
  /** 打赏 */
  REWARD = '/pages/reward/index',
  /** 聊天室 */
  CHATING = '/pages/im/chating/index',
  /** 视频聊天 */
  VIDEO_CALL = '/pages/im/videocall/index',

  /** 支付中心(旧) */
  PAYMENT = '/pages/payment/index',
  /** 支付结果页(旧) */
  PAYMENT_RESULT = '/pages/payment/result/index',
}

export default PAGE;
